trigger:
  branches:
    include:
      - none

jobs:
  - job: PushToGitHub
    displayName: 'Push to GitHub'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - checkout: self

      - script: |
          git config --global user.email "agmahesh253@gmail.com"
          git config --global user.name "agmahesh253"
          git remote remove origin || true
          git remote add origin https://github.com/agmahesh253/Adobe-Magento.git
          git remote set-url --add --push origin https://agmahesh253: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@github.com/agmahesh253/Test_demo.git
          git remote -v
          git pull --rebase origin main
          git push origin HEAD:main --force
        displayName: 'Push to GitHub'
